#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/live-config" ]; then
		update-rc.d live-config start 00 S . >/dev/null || exit $?
	fi
fi
# End automatically added section
